### ISSUE TITLE
Examples of XML parsers

### ISSUE THREAD

**Issue by KirillOsenkov** [wieslawsoltes/XmlParser#1]
Hey, if you're looking into parsing XML here are a couple of links (just in case!):

 * https://github.com/KirillOsenkov/XmlParser
 * https://github.com/mhutch/MonoDevelop.Xml

Both have their strengths and weaknesses, but both are interesting.
The first one is very Roslyn-like, with full fidelity (whitespace/trivia), immutable red-green trees, incremental parsing.
The second one is very interesting and composed of the main loop and an extensible state machine.

**Comment by wieslawsoltes** [comment]
@KirillOsenkov Thank you for your interest and parser links. 

My interest into xaml parser is very specific and had or has narrow objective, I need parser that has very little memory allocation overhead and can be easily benchmarked. 

My main goal is to limit allocations and be very fast. The conformance level has just be enough to parse Svg test suite that I am working on.

**Comment by wieslawsoltes** [comment]
For reference this is my current work (part of larger ongoing effort) https://github.com/svg-net/SVG/pull/813

**Comment by KirillOsenkov** [comment]
Yes, both parsers I mentioned are pretty heavyweight and designed for IDE support and allocatey.

Have you looked at raw XmlReader? It should be pretty fast.

**Comment by wieslawsoltes** [comment]
> Have you looked at raw XmlReader? It should be pretty fast.

Yes, it is really fast, but creating XmlReader allocates 10kB and when I have 100 byte Svg file that's a lot for my use case. I have benchmarks with XmlReader in the repo.
